version: '2'
services:

  db:
    image: mariadb:10.1
    container_name: toomtam_mariadb
    restart: always
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123132123
      - MYSQL_DATABASE=lemp_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456

  php:
    build: ./
    container_name: toomtam_php-fpm
    restart: always
    volumes:
      - ./www/:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: toomtam_nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    volumes_from:
      - php
    ports:
      - 80:80
      
  pma:
      image: phpmyadmin/phpmyadmin
      container_name: toomtam-phpmyadmin
      restart: always
      ports:
        - "9000:80"
